/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioScenesRouteImport } from './routes/studio.scenes'
import { Route as StudioScalesRouteImport } from './routes/studio.scales'
import { Route as StudioPacksRouteImport } from './routes/studio.packs'
import { Route as AdminUnlockRouteImport } from './routes/admin.unlock'
import { Route as AdminScenesRouteImport } from './routes/admin.scenes'
import { Route as AdminScalesRouteImport } from './routes/admin.scales'
import { Route as AdminPacksRouteImport } from './routes/admin.packs'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioScenesRoute = StudioScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => StudioRoute,
} as any)
const StudioScalesRoute = StudioScalesRouteImport.update({
  id: '/scales',
  path: '/scales',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPacksRoute = StudioPacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => StudioRoute,
} as any)
const AdminUnlockRoute = AdminUnlockRouteImport.update({
  id: '/admin/unlock',
  path: '/admin/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScenesRoute = AdminScenesRouteImport.update({
  id: '/admin/scenes',
  path: '/admin/scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScalesRoute = AdminScalesRouteImport.update({
  id: '/admin/scales',
  path: '/admin/scales',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPacksRoute = AdminPacksRouteImport.update({
  id: '/admin/packs',
  path: '/admin/packs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/studio': typeof StudioRouteWithChildren
  '/admin/packs': typeof AdminPacksRoute
  '/admin/scales': typeof AdminScalesRoute
  '/admin/scenes': typeof AdminScenesRoute
  '/admin/unlock': typeof AdminUnlockRoute
  '/studio/packs': typeof StudioPacksRoute
  '/studio/scales': typeof StudioScalesRoute
  '/studio/scenes': typeof StudioScenesRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/packs': typeof AdminPacksRoute
  '/admin/scales': typeof AdminScalesRoute
  '/admin/scenes': typeof AdminScenesRoute
  '/admin/unlock': typeof AdminUnlockRoute
  '/studio/packs': typeof StudioPacksRoute
  '/studio/scales': typeof StudioScalesRoute
  '/studio/scenes': typeof StudioScenesRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/studio': typeof StudioRouteWithChildren
  '/admin/packs': typeof AdminPacksRoute
  '/admin/scales': typeof AdminScalesRoute
  '/admin/scenes': typeof AdminScenesRoute
  '/admin/unlock': typeof AdminUnlockRoute
  '/studio/packs': typeof StudioPacksRoute
  '/studio/scales': typeof StudioScalesRoute
  '/studio/scenes': typeof StudioScenesRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/studio'
    | '/admin/packs'
    | '/admin/scales'
    | '/admin/scenes'
    | '/admin/unlock'
    | '/studio/packs'
    | '/studio/scales'
    | '/studio/scenes'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/packs'
    | '/admin/scales'
    | '/admin/scenes'
    | '/admin/unlock'
    | '/studio/packs'
    | '/studio/scales'
    | '/studio/scenes'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/studio'
    | '/admin/packs'
    | '/admin/scales'
    | '/admin/scenes'
    | '/admin/unlock'
    | '/studio/packs'
    | '/studio/scales'
    | '/studio/scenes'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  StudioRoute: typeof StudioRouteWithChildren
  AdminPacksRoute: typeof AdminPacksRoute
  AdminScalesRoute: typeof AdminScalesRoute
  AdminScenesRoute: typeof AdminScenesRoute
  AdminUnlockRoute: typeof AdminUnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/scenes': {
      id: '/studio/scenes'
      path: '/scenes'
      fullPath: '/studio/scenes'
      preLoaderRoute: typeof StudioScenesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/scales': {
      id: '/studio/scales'
      path: '/scales'
      fullPath: '/studio/scales'
      preLoaderRoute: typeof StudioScalesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/packs': {
      id: '/studio/packs'
      path: '/packs'
      fullPath: '/studio/packs'
      preLoaderRoute: typeof StudioPacksRouteImport
      parentRoute: typeof StudioRoute
    }
    '/admin/unlock': {
      id: '/admin/unlock'
      path: '/admin/unlock'
      fullPath: '/admin/unlock'
      preLoaderRoute: typeof AdminUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scenes': {
      id: '/admin/scenes'
      path: '/admin/scenes'
      fullPath: '/admin/scenes'
      preLoaderRoute: typeof AdminScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scales': {
      id: '/admin/scales'
      path: '/admin/scales'
      fullPath: '/admin/scales'
      preLoaderRoute: typeof AdminScalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packs': {
      id: '/admin/packs'
      path: '/admin/packs'
      fullPath: '/admin/packs'
      preLoaderRoute: typeof AdminPacksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioRouteChildren {
  StudioPacksRoute: typeof StudioPacksRoute
  StudioScalesRoute: typeof StudioScalesRoute
  StudioScenesRoute: typeof StudioScenesRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioPacksRoute: StudioPacksRoute,
  StudioScalesRoute: StudioScalesRoute,
  StudioScenesRoute: StudioScenesRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  StudioRoute: StudioRouteWithChildren,
  AdminPacksRoute: AdminPacksRoute,
  AdminScalesRoute: AdminScalesRoute,
  AdminScenesRoute: AdminScenesRoute,
  AdminUnlockRoute: AdminUnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
